import { db } from '@/db';
import { jobs } from '@/db/schema';

async function main() {
    const now = new Date();
    
    const sampleJobs = [
        // Tech Giants - Entry Level
        {
            title: 'Software Engineer - New Grad',
            company: 'Google',
            description: 'Join our team to build scalable systems that impact billions of users. Work on cutting-edge technologies and collaborate with world-class engineers. Recent CS graduates welcome.',
            location: 'Mountain View',
            salaryMin: 120000,
            salaryMax: 160000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Frontend Developer',
            company: 'Microsoft',
            description: 'Build beautiful and intuitive user interfaces for Microsoft 365 products. Work with React, TypeScript, and modern web technologies. Strong foundation in web development required.',
            location: 'Seattle',
            salaryMin: 110000,
            salaryMax: 150000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Data Analyst',
            company: 'Amazon',
            description: 'Analyze large datasets to drive business decisions for AWS products. Use SQL, Python, and data visualization tools to uncover insights. Entry-level position with mentorship opportunities.',
            location: 'Seattle',
            salaryMin: 85000,
            salaryMax: 120000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 50 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'iOS Developer',
            company: 'Apple',
            description: 'Develop innovative features for iOS applications used by millions worldwide. Work with Swift, SwiftUI, and Apple\'s latest frameworks. Passion for creating exceptional user experiences required.',
            location: 'Cupertino',
            salaryMin: 130000,
            salaryMax: 170000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 40 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Backend Engineer',
            company: 'Meta',
            description: 'Build scalable backend services for Facebook, Instagram, and WhatsApp. Work with distributed systems, databases, and microservices architecture. New graduates encouraged to apply.',
            location: 'Menlo Park',
            salaryMin: 125000,
            salaryMax: 165000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 55 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // Startups - Entry Level
        {
            title: 'Full Stack Developer',
            company: 'Stripe',
            description: 'Help build the economic infrastructure for the internet. Work on payment APIs, developer tools, and internal platforms. Strong programming fundamentals required.',
            location: 'San Francisco',
            salaryMin: 115000,
            salaryMax: 155000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 35 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Product Designer',
            company: 'Figma',
            description: 'Design the future of collaborative design tools. Create intuitive interfaces and delightful user experiences. Portfolio showcasing design thinking required.',
            location: 'San Francisco',
            salaryMin: 95000,
            salaryMax: 130000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Software Engineer',
            company: 'Airbnb',
            description: 'Build features that help travelers find their perfect accommodations. Work on web and mobile platforms using React and React Native. Experience with JavaScript frameworks preferred.',
            location: 'San Francisco',
            salaryMin: 110000,
            salaryMax: 145000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 50 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Frontend Engineer',
            company: 'Notion',
            description: 'Create beautiful, fast, and reliable web experiences for the all-in-one workspace. Work with React, TypeScript, and modern web technologies. Passion for product quality essential.',
            location: 'Remote',
            salaryMin: 100000,
            salaryMax: 135000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: null,
            status: 'active',
            createdAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // Mid-level positions
        {
            title: 'Senior Frontend Developer',
            company: 'Shopify',
            description: 'Lead frontend development for merchant-facing features. Mentor junior developers and drive technical decisions. 3+ years of React experience required.',
            location: 'Toronto',
            salaryMin: 120000,
            salaryMax: 160000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 40 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Data Scientist',
            company: 'Netflix',
            description: 'Apply machine learning to improve content recommendations and user engagement. Work with large-scale datasets and cutting-edge ML frameworks. MS or PhD in related field preferred.',
            location: 'Los Angeles',
            salaryMin: 140000,
            salaryMax: 180000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'DevOps Engineer',
            company: 'Slack',
            description: 'Build and maintain infrastructure for millions of daily active users. Implement CI/CD pipelines and monitoring solutions. Experience with Kubernetes and AWS required.',
            location: 'San Francisco',
            salaryMin: 130000,
            salaryMax: 170000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Product Manager',
            company: 'Zoom',
            description: 'Drive product strategy for video conferencing features. Work closely with engineering and design teams to deliver user-centric solutions. 3+ years of product management experience required.',
            location: 'San Jose',
            salaryMin: 135000,
            salaryMax: 175000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 55 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Mobile Developer',
            company: 'Uber',
            description: 'Develop features for Uber\'s rider and driver apps. Work with native iOS or Android technologies. Experience shipping production mobile apps required.',
            location: 'San Francisco',
            salaryMin: 125000,
            salaryMax: 165000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 50 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // Senior positions
        {
            title: 'Staff Software Engineer',
            company: 'Google',
            description: 'Lead technical direction for critical infrastructure projects. Mentor engineers and drive architectural decisions. 8+ years of experience in distributed systems required.',
            location: 'Mountain View',
            salaryMin: 180000,
            salaryMax: 250000,
            jobType: 'full-time',
            experienceLevel: 'senior',
            postedDate: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 70 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Principal Engineer',
            company: 'Amazon',
            description: 'Define technical vision and strategy for AWS services. Lead cross-functional teams and drive innovation. Proven track record of delivering large-scale systems required.',
            location: 'Seattle',
            salaryMin: 200000,
            salaryMax: 280000,
            jobType: 'full-time',
            experienceLevel: 'senior',
            postedDate: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 80 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Engineering Manager',
            company: 'Microsoft',
            description: 'Lead a team of 8-10 engineers building cloud infrastructure. Balance technical leadership with people management. 6+ years of engineering experience with 2+ years managing teams required.',
            location: 'Redmond',
            salaryMin: 170000,
            salaryMax: 220000,
            jobType: 'full-time',
            experienceLevel: 'senior',
            postedDate: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 65 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // Remote positions
        {
            title: 'Backend Developer',
            company: 'GitLab',
            description: 'Work on Ruby on Rails application serving millions of developers. Build scalable APIs and optimize database performance. Remote-first company culture.',
            location: 'Remote',
            salaryMin: 90000,
            salaryMax: 125000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: null,
            status: 'active',
            createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'UX Designer',
            company: 'Atlassian',
            description: 'Design intuitive experiences for Jira and Confluence users. Conduct user research and create design systems. Portfolio demonstrating UX process required.',
            location: 'Remote',
            salaryMin: 105000,
            salaryMax: 140000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 50 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Technical Writer',
            company: 'MongoDB',
            description: 'Create clear, comprehensive documentation for database products. Work with engineering teams to explain complex concepts. Strong writing skills and technical background required.',
            location: 'Remote',
            salaryMin: 75000,
            salaryMax: 105000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // Internships
        {
            title: 'Software Engineering Intern',
            company: 'Google',
            description: 'Summer internship working on production systems. Contribute to real projects with mentorship from senior engineers. Currently pursuing CS degree required.',
            location: 'Mountain View',
            salaryMin: 8000,
            salaryMax: 10000,
            jobType: 'internship',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Data Science Intern',
            company: 'Meta',
            description: 'Apply machine learning to real-world problems. Work with large datasets and build predictive models. Pursuing MS or PhD in data science or related field.',
            location: 'Menlo Park',
            salaryMin: 9000,
            salaryMax: 11000,
            jobType: 'internship',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 35 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'UX Design Intern',
            company: 'Apple',
            description: 'Design user interfaces for Apple products. Collaborate with designers and engineers. Portfolio showcasing design projects required.',
            location: 'Cupertino',
            salaryMin: 7500,
            salaryMax: 9500,
            jobType: 'internship',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 40 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Product Management Intern',
            company: 'Amazon',
            description: 'Work on product features for AWS services. Conduct user research and define product requirements. MBA students or technical undergrads welcome.',
            location: 'Seattle',
            salaryMin: 8500,
            salaryMax: 10500,
            jobType: 'internship',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 27 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 33 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 27 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 27 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Marketing Intern',
            company: 'Stripe',
            description: 'Support marketing campaigns for developer products. Create content and analyze campaign performance. Interest in technology and marketing required.',
            location: 'San Francisco',
            salaryMin: 6500,
            salaryMax: 8000,
            jobType: 'internship',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 38 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'DevOps Intern',
            company: 'Netflix',
            description: 'Learn about cloud infrastructure and deployment automation. Work with Kubernetes, Docker, and CI/CD pipelines. Pursuing degree in CS or related field.',
            location: 'Los Angeles',
            salaryMin: 8000,
            salaryMax: 9500,
            jobType: 'internship',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 42 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // Traditional Enterprises
        {
            title: 'Cloud Solutions Architect',
            company: 'IBM',
            description: 'Design and implement cloud solutions for enterprise clients. Work with hybrid cloud technologies and advise on migration strategies. 5+ years of cloud experience required.',
            location: 'New York',
            salaryMin: 140000,
            salaryMax: 180000,
            jobType: 'full-time',
            experienceLevel: 'senior',
            postedDate: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Database Administrator',
            company: 'Oracle',
            description: 'Manage and optimize Oracle database systems for enterprise clients. Ensure high availability and performance. Oracle certification preferred.',
            location: 'Austin',
            salaryMin: 95000,
            salaryMax: 130000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 55 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'CRM Developer',
            company: 'Salesforce',
            description: 'Customize and extend Salesforce platform for clients. Build Lightning components and integrate with external systems. Salesforce certifications a plus.',
            location: 'San Francisco',
            salaryMin: 100000,
            salaryMax: 135000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 50 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // Part-time and Contract positions
        {
            title: 'Frontend Developer',
            company: 'WordPress',
            description: 'Build WordPress themes and plugins on a contract basis. Work with PHP, JavaScript, and WordPress APIs. Flexible schedule with remote work.',
            location: 'Remote',
            salaryMin: 50,
            salaryMax: 75,
            jobType: 'contract',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: null,
            status: 'active',
            createdAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Content Writer',
            company: 'Medium',
            description: 'Write technical articles and blog posts on a freelance basis. Cover topics like web development, design, and technology trends. Strong writing portfolio required.',
            location: 'Remote',
            salaryMin: 40,
            salaryMax: 60,
            jobType: 'contract',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: null,
            status: 'active',
            createdAt: new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'QA Tester',
            company: 'Dropbox',
            description: 'Test software applications part-time. Write test cases and report bugs. Attention to detail and basic technical knowledge required.',
            location: 'San Francisco',
            salaryMin: 30000,
            salaryMax: 45000,
            jobType: 'part-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 48 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // Additional diverse positions
        {
            title: 'Machine Learning Engineer',
            company: 'Tesla',
            description: 'Develop ML models for autonomous driving systems. Work with computer vision and deep learning. MS or PhD in ML, robotics, or related field required.',
            location: 'Palo Alto',
            salaryMin: 150000,
            salaryMax: 200000,
            jobType: 'full-time',
            experienceLevel: 'senior',
            postedDate: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 65 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Security Engineer',
            company: 'Cloudflare',
            description: 'Protect internet infrastructure from cyber threats. Build security tools and respond to incidents. Strong background in security and networking required.',
            location: 'Austin',
            salaryMin: 130000,
            salaryMax: 170000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 52 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Business Analyst',
            company: 'Salesforce',
            description: 'Analyze business requirements and translate them into technical specifications. Bridge gap between business and technology teams. Strong analytical skills required.',
            location: 'Chicago',
            salaryMin: 80000,
            salaryMax: 110000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 47 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Platform Engineer',
            company: 'Twilio',
            description: 'Build and maintain developer platforms and APIs. Ensure reliability and scalability of communication services. Experience with distributed systems required.',
            location: 'Denver',
            salaryMin: 115000,
            salaryMax: 150000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 54 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'React Native Developer',
            company: 'Discord',
            description: 'Build cross-platform mobile features for Discord app. Work with React Native, TypeScript, and native modules. Experience shipping mobile apps required.',
            location: 'San Francisco',
            salaryMin: 110000,
            salaryMax: 145000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 49 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Site Reliability Engineer',
            company: 'Datadog',
            description: 'Ensure reliability and performance of monitoring infrastructure. Build automation tools and improve system observability. Strong Linux and cloud experience required.',
            location: 'New York',
            salaryMin: 135000,
            salaryMax: 175000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 58 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Growth Engineer',
            company: 'Duolingo',
            description: 'Drive user acquisition and retention through data-driven experiments. Build features that improve engagement metrics. Strong full-stack skills and analytical mindset required.',
            location: 'Pittsburgh',
            salaryMin: 105000,
            salaryMax: 140000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 46 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Embedded Systems Engineer',
            company: 'Nvidia',
            description: 'Develop software for GPU and embedded systems. Work on low-level drivers and firmware. Strong C/C++ and hardware knowledge required.',
            location: 'Santa Clara',
            salaryMin: 125000,
            salaryMax: 165000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 62 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Analytics Engineer',
            company: 'Snowflake',
            description: 'Build data models and analytics pipelines. Work with SQL, Python, and modern data tools. Strong data warehousing knowledge required.',
            location: 'San Francisco',
            salaryMin: 110000,
            salaryMax: 145000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 51 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'UI Engineer',
            company: 'Vercel',
            description: 'Build beautiful, performant web interfaces. Work with Next.js, React, and modern CSS. Strong eye for design and attention to detail required.',
            location: 'Remote',
            salaryMin: 100000,
            salaryMax: 135000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: null,
            status: 'active',
            createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Blockchain Developer',
            company: 'Coinbase',
            description: 'Build decentralized applications and smart contracts. Work with Ethereum, Solidity, and Web3 technologies. Passion for crypto and blockchain required.',
            location: 'San Francisco',
            salaryMin: 120000,
            salaryMax: 160000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 56 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Automation Engineer',
            company: 'Zapier',
            description: 'Build workflow automation features connecting thousands of apps. Work with APIs, webhooks, and distributed systems. Strong backend development skills required.',
            location: 'Remote',
            salaryMin: 105000,
            salaryMax: 140000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: null,
            status: 'active',
            createdAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Computer Vision Engineer',
            company: 'Snap',
            description: 'Develop AR filters and computer vision features for Snapchat. Work with machine learning, image processing, and real-time systems. Strong ML background required.',
            location: 'Los Angeles',
            salaryMin: 140000,
            salaryMax: 180000,
            jobType: 'full-time',
            experienceLevel: 'senior',
            postedDate: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 68 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Infrastructure Engineer',
            company: 'DigitalOcean',
            description: 'Build and scale cloud infrastructure for developers. Work with Kubernetes, networking, and distributed systems. Strong systems programming skills required.',
            location: 'New York',
            salaryMin: 115000,
            salaryMax: 150000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 53 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Technical Program Manager',
            company: 'Lyft',
            description: 'Drive technical initiatives across engineering teams. Coordinate complex projects and remove blockers. Technical background with strong PM skills required.',
            location: 'San Francisco',
            salaryMin: 130000,
            salaryMax: 170000,
            jobType: 'full-time',
            experienceLevel: 'senior',
            postedDate: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 59 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Test Engineer',
            company: 'Spotify',
            description: 'Develop automated testing frameworks for music streaming services. Ensure quality across web, mobile, and desktop platforms. Strong testing and coding skills required.',
            location: 'Boston',
            salaryMin: 95000,
            salaryMax: 130000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 48 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Solutions Engineer',
            company: 'HashiCorp',
            description: 'Help customers adopt infrastructure automation tools. Provide technical guidance and build proof of concepts. Strong DevOps and cloud experience required.',
            location: 'Remote',
            salaryMin: 110000,
            salaryMax: 145000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 23 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: null,
            status: 'active',
            createdAt: new Date(now.getTime() - 23 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Game Developer',
            company: 'Unity',
            description: 'Build features for Unity game engine. Work on graphics, physics, or editor tools. Strong C++ or C# skills and passion for gaming required.',
            location: 'San Francisco',
            salaryMin: 105000,
            salaryMax: 140000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 26 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 44 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 26 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'API Developer',
            company: 'Postman',
            description: 'Build and maintain REST and GraphQL APIs. Create API documentation and developer tools. Strong backend development and API design skills required.',
            location: 'Remote',
            salaryMin: 95000,
            salaryMax: 130000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: null,
            status: 'active',
            createdAt: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Customer Success Engineer',
            company: 'Zendesk',
            description: 'Help customers succeed with customer support platform. Provide technical guidance and build integrations. Strong communication and technical skills required.',
            location: 'San Francisco',
            salaryMin: 85000,
            salaryMax: 115000,
            jobType: 'full-time',
            experienceLevel: 'entry',
            postedDate: new Date(now.getTime() - 29 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 41 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 29 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 29 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Research Engineer',
            company: 'OpenAI',
            description: 'Conduct research on large language models and AI safety. Implement and scale cutting-edge ML algorithms. PhD or strong research experience required.',
            location: 'San Francisco',
            salaryMin: 160000,
            salaryMax: 220000,
            jobType: 'full-time',
            experienceLevel: 'senior',
            postedDate: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 75 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Developer Advocate',
            company: 'GitHub',
            description: 'Represent GitHub in developer community. Create content, speak at conferences, and gather feedback. Strong technical background and communication skills required.',
            location: 'Remote',
            salaryMin: 110000,
            salaryMax: 145000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: null,
            status: 'active',
            createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Performance Engineer',
            company: 'Cloudinary',
            description: 'Optimize media delivery and processing performance. Build CDN integrations and improve load times. Strong systems knowledge and optimization skills required.',
            location: 'Remote',
            salaryMin: 115000,
            salaryMax: 150000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 57 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Accessibility Engineer',
            company: 'Adobe',
            description: 'Make Adobe products accessible to users with disabilities. Implement WCAG standards and build accessible components. Passion for inclusive design required.',
            location: 'San Jose',
            salaryMin: 100000,
            salaryMax: 135000,
            jobType: 'full-time',
            experienceLevel: 'mid',
            postedDate: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            applicationDeadline: new Date(now.getTime() + 43 * 24 * 60 * 60 * 1000).toISOString(),
            status: 'active',
            createdAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(jobs).values(sampleJobs);
    
    console.log('✅ Jobs seeder completed successfully - 60 job listings created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});